import type { Metadata } from "next";
import { Alumni_Sans } from "next/font/google";
import "./globals.css";
import { NavLinks } from "./components/NavLinks";

const alumni = Alumni_Sans({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Житня Сльоза",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alumni.className} flex justify-center flex-col bg-black`}>
        <NavLinks />
        {children}
      </body>
    </html>
  );
}
