import type { Metadata } from "next";
import { Alumni_Sans } from "next/font/google";
import "./globals.css";
import  NavBar  from "./components/NavBar/NavBar";

const alumni = Alumni_Sans({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Житня Сльоза",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body className={`${alumni.className} flex justify-center flex-col bg-black text-white`}>
        <NavBar/>
        
        {children}
      </body>
    </html>
  );
}
